Page create - Recycle Bin Check
oqtane/oqtane.framework pull request #1646
Opened 2021-09-08 06:09 UTC by leigh-pointer

After Delete Page, Cant create page of same name #1645 issue. Added check and message if the page is in the recycle bin.

2021-09-08 08:06 UTC, hishamco requested changes
This check may be a workaround, the good solution is allow to create a page with the same name

2021-09-08 08:06 UTC, hishamco commented on Oqtane.Client/Modules/Admin/Pages/Add.razor
> +    private static bool PagePathIsDeleted(string pagePath, int siteId, List<Page> existingPages)
I suggest to move the LINQ query before the condition

2021-09-08 08:06 UTC, hishamco commented on Oqtane.Client/Modules/Admin/Pages/Add.razor
> +                        return;
Add line break before 'return`

2021-09-08 08:14 UTC, leigh-pointer commented
> This check may be a workaround, the good solution is allow to create a page with the same name

you can't create a page with the same name because the database table Page has a UNIQUE NONCLUSTERED INDEX on it consisting of fields [SiteId],[Path],[UserId].

2021-09-09 05:24 UTC, hishamco commented
You're right, I know that, but we may change this to make it an optimal solution

/cc @sbwalker

2021-09-10 12:25 UTC, sbwalker commented
@leigh-pointer are you sure the logic below is correct? The condition "!PagePathIsDeleted()" seems to be saying "if the page is NOT deleted" then show the warning message - which does not seem accurate?

```
if(!PagePathIsDeleted(page.Path, page.SiteId, _pageList))
{
     AddModuleMessage(string.Format(Localizer["Message.Page.Deleted"], _path), MessageType.Warning);
    return;
}

2021-09-10 17:02 UTC, closed without merging