[ENAHNCE] - Added TextBox to Action Dialog
oqtane/oqtane.framework pull request #3470
Opened 2023-11-12 04:36 UTC by vnetonline

2023-11-16 19:54 UTC, sbwalker commented
@vnetonline I have been focused on the 5.0 release... I will have feedback on this PR soon...

2023-11-17 09:51 UTC, hishamco requested changes

2023-11-17 09:51 UTC, hishamco commented on .gitignore
> +Oqtane.Server/wwwroot/_content/syncfusion.*
Seems this is custom to your project

2023-11-17 09:51 UTC, hishamco commented on .gitignore
> +/Oqtane.Server/appsettings.json
Why?!!

2023-11-17 09:51 UTC, hishamco commented on Oqtane.Client/Modules/Controls/ActionDialog.razor
> +    public bool ShowTextBox { get; set; } = false; // optional - specifies if the TextBox should be displayed in the dialog - default is false
I can't entirely agree with this because we might have multiple inputs, so it would be nice to have the body as a template

2023-11-17 09:51 UTC, hishamco commented on Oqtane.Client/Modules/Controls/ActionDialog.razor
> +    public EventCallback<string> OnClose { get; set; } // optional - executes a method in the calling component when the Modal is Closed
I like to introduce event callback in such components as extensibility point, @sbwalker we might need to revise the available components

2023-11-18 22:25 UTC, vnetonline commented
I will submit another pull request that uses `RenderFragment` for `Header`,  `Body` and `Footer` closing this as it is not flexible enough as pointed out by @hishamco 

Closing this pull request because it also has commits that relate to `syncfusion` and `.gitignore`

2023-11-18 22:25 UTC, closed without merging